import { useRouter } from "next/router";
import Link from "next/link";
import useSWR from "swr";
import Head from "next/head";
import Image from "next/image";
// Components
import Game from "components/game";
// Styles
import styles from "../styles/Home.module.css";
import { ILangData } from "../api/data";

const fetcher = (lang: string) =>
  fetch(`/api/data?lang=${lang}`)
    .then((response) => response.json())
    .catch((err) => console.log(err));

export default function Home() {
  const query = useRouter().query;
  const { data, error } = useSWR<ILangData>(query.lang!, fetcher);

  if (error) return <h1>Error...</h1>;
  if (!data) return <h1>Loading....</h1>;

  return (
    <div>
      <Head>
        <title>Web Speech Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <Link href="/">
            <a>
              usePairs(
              <Image
                src="/bird.png"
                alt="UsePairs Logo"
                width={42}
                height={42}
              />
              )
            </a>
          </Link>
        </h1>

        <Game data={data} />
      </main>

      <footer></footer>
    </div>
  );
}
